# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'af2cbec6-e307-42a1-9def-4e4dabeac522'
  imageRepository: 'psergeiupworkdevempowerid'
  containerRegistry: 'prognimakdevaksregistry.azurecr.io'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'prognimakdevaksregistry37fd-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build_demo
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'prognimakdevaksregistry'
        command: 'buildAndPush'
        Dockerfile: 'demo/Dockerfile'
        buildContext: 'demo'

    - upload: manifests
      artifact: manifests


