trigger:
- master

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'af2cbec6-e307-42a1-9def-4e4dabeac522'
  imageRepository: 'psergeiupworkdevempowerid'
  containerRegistry: 'prognimakdevaksregistry.azurecr.io'
  imagePullSecret: 'prognimakdevaksregistry37fd-auth'

pool:
  # Agent VM image name
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'prognimakdevaksregistry'
    command: 'buildAndPush'
    Dockerfile: 'demo/Dockerfile'
    buildContext: 'demo'


